# Generated by Django 5.0.2 on 2024-03-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetsphere', '0002_calendar_contact_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
